### PR TITLE
More GUI improvements for patient list and patient form pages

### PR DESCRIPTION
**Pull request by angusYuhao**

### CODE REVIEW

**Comment by xieanne** [comment]
lmao do u guys mind taking a screenshot LOOOOOOL cuz i can't run it :(

**Review by liu-allan — APPROVED** [review]

**Comment by ianyechen** [comment]
> lmao do u guys mind taking a screenshot LOOOOOOL cuz i can't run it :(

image

**Comment by ianyechen** [comment]
> lmao do u guys mind taking a screenshot LOOOOOOL cuz i can't run it :(

hmm wait how come you aren't able to run it? I think it's probably fine for you to fetch and checkout this branch without the MATLAB engine? You can either comment out the code for the model part or just don't press the calculate button?

**Review by ianyechen — APPROVED** [review]
LGTM, the animation is awesome. Thanks!

**Pull request merged**
