### PR TITLE
Add consent field

### PR DESCRIPTION
**Pull request by liu-allan**
#73

### CODE REVIEW

**Review by xieanne — APPROVED** [review]
Can you take a screenshot cuz i can't run that code :(

**Comment by liu-allan** [comment]
> Can you take a screenshot cuz i can't run that code :(

image

**Comment by xieanne** [comment]
LGTM

**Review by ianyechen — CHANGES_REQUESTED** [review]
I think we should "reset" the checkbox every time this page is loaded. Right now, if you add a patient and then add another patient, the checkbox is ticked initially when you go add a second patient.

**Comment by ianyechen** [comment]
Also, when the phone number field is left empty, the patient can still be signed up. Is that intended? Does the "input fields must not be empty" not apply to non-essential fields?

**Comment by liu-allan** [comment]
> I think we should "reset" the checkbox every time this page is loaded. Right now, if you add a patient and then add another patient, the checkbox is ticked initially when you go add a second patient.

Thanks, good catch!

**Comment by liu-allan** [comment]
> Also, when the phone number field is left empty, the patient can still be signed up. Is that intended? Does the "input fields must not be empty" not apply to non-essential fields?

I have fixed it so it now checks that phone number is not empty

**Review by ianyechen — APPROVED** [review]
LGTM

**Pull request merged**
