### PR TITLE
Implement encryption to all fields in the patients table

### PR DESCRIPTION
**Pull request by ianyechen**
1. Every column in the `patients` table is now encrypted with the exception of the `oncologist_id` field (this column is a foreign key which references the `username` field of the `oncologists` table where it acts as the primary key. If we were to encrypt that, there would be possibilities of duplicate usernames since the password, which is currently used as the encryption key is going to be different, resulting in a different encrypted text, but with actually the same plain text) 
image
2. Removed the cancel button on the Patient Information page. We already have the Patient List icon on the left, this button is redundant and misleading. 
image
3. Added the `gender` field to the `patients` table. Not yet integrated with @xieanne's changes.

### CODE REVIEW

**Review by angusYuhao — CHANGES_REQUESTED** [review]
Looks good. However I think "gender" should be changed to "sex" in medical context.

**Comment by ianyechen** [comment]
> Looks good. However I think "gender" should be changed to "sex" in medical context.

good idea, done

**Review by liu-allan — APPROVED** [review]
When saving the dosage and measurement, shouldn't patient_id be hashed as well? If this is too much I don't really care.

**Comment by ianyechen** [comment]
> When saving the dosage and measurement, shouldn't patient_id be hashed as well? If this is too much I don't really care.

`patient_id` is the column in the `measurements` table that references the `id` in the `patients` table as a foreign key, that is simply a SQLite generated integer (1,2,3), I don't think encrypting this is necessary. Sorry for the misunderstanding!

**Review by xieanne — APPROVED** [review]
COOL STUFF

**Review by angusYuhao — APPROVED** [review]
good work!

**Pull request merged**
