### PR TITLE
Minor patient list fixes

### PR DESCRIPTION
**Pull request by angusYuhao**
1. reset fields and buttons upon new entry into the page
2. add phone number field on patient list
3. tuned some spacing

### CODE REVIEW

**Comment by angusYuhao** [comment]
very small change to fix some issues on patient list page. Please review so we can merge

**Review by liu-allan — COMMENTED** [review]
image

Looks good, can you change the scale of the graph to reflect the canva screenshot?

**Comment by ianyechen** [comment]
> image
> 
> Looks good, can you change the scale of the graph to reflect the canva screenshot?

this can be done by using the right mouse cursor to adjust the scaling, @liu-allan suggested we put this down on the README. I think we should do that too.

also @angusYuhao the table looks great, is it possible to enlarge the texts in the table though?

**Review by liu-allan — APPROVED** [review]

**Review by ianyechen — APPROVED** [review]
LGTM

**Pull request merged**
